apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
      - name: targeting-service
        image: 239510186324.dkr.ecr.us-east-1.amazonaws.com/targeting-service:latest
        ports:
        - containerPort: 8080