apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: 239510186324.dkr.ecr.us-east-1.amazonaws.com/auth-service:052ec12f0571638774980e11df95a135f8d5033c
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: togglemaster-secrets
              key: AUTH_DATABASE_URL
        - name: SERVICE_API_KEY
          valueFrom:
            secretKeyRef:
              name: togglemaster-secrets
              key: SERVICE_API_KEY
        - name: MASTER_KEY
          valueFrom:
            secretKeyRef:
              name: togglemaster-secrets
              key: MASTER_KEY
