apiVersion: apps/v1
kind: Deployment
metadata:
  name: flag-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flag-service
  template:
    metadata:
      labels:
        app: flag-service
    spec:
      containers:
      - name: flag-service
        image: 239510186324.dkr.ecr.us-east-1.amazonaws.com/flag-service:27f1da3994a1426c75af27a82cd8ebfeb950084a
        ports:
        - containerPort: 8080